import Head from 'next/head'
import conectarDB from '../../lib/dbConnect'
import Pelicula from '../../models/Pelicula'
import Link from 'next/link'

export default function Home({peliculas}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <h1>Peliculas</h1>
        <Link href='/new'>
        <button className='btn btn-success w-100 mb-2'>Agregar pelicula</button>
        </Link>
        {
          peliculas.map (({_id, title, descripcion}) =>(
            <div className="card mb-2" key={_id}>
              <card className="body">
                <div className="h5 text-uppercase">{title}</div>
                <p className="fw-light">{descripcion}</p>  
                <Link href={`/${_id}`} className='btn btn-success me-2'>
                        Detalle
                    </Link>
              </card>
            </div>
            
          ))
        }
      </main>
    </>
  )
}

export async function getServerSideProps (){
  try{
    await conectarDB()
    const resultado = await Pelicula.find()
  
    const peliculas = resultado.map(doc => {
      const pelicula = doc.toObject()
      pelicula._id = pelicula._id.toString()
      return pelicula
    })

    return {props:{peliculas}}
  }catch(error){
    console.log(error)
    return {props:{success: false, error: 'errorpa'}}
  }
}
